#!/usr/bin/env bash

fzf="fzf --height 40% --layout=reverse --border"

# pick h5 file
file=$(ls *.h5 *.hdf5 2>/dev/null | $fzf)
[[ -z "$file" ]] && echo "No file selected" && exit

# pick operation
option=$(printf "list\ndel" | $fzf)
[[ -z "$option" ]] && exit

if [[ $option == "list" ]]; then
    h5ls -lr "$file"
    exit
fi

# delete mode
del_options=$(printf "group\ndataset" | $fzf)
[[ -z "$del_options" ]] && exit

# SELECT GROUPS
if [[ $del_options == "group" ]]; then
    groups=$(h5ls -lr "$file" | awk '/Group/ {print $1}' | sed 's/://g')

    selected=$(printf "%s\n" "$groups" | $fzf --multi --border-label " Select group(s) to delete ")
    [[ -z "$selected" ]] && echo "No groups selected." && exit

    # Build delete args
    delete_args=""
    while IFS= read -r g; do
        delete_args="$delete_args -d $g"
    done <<< "$selected"

    echo "Deleting: $selected"
    python h5x.py delete "$file" $delete_args
    exit
fi

# SELECT DATASETS
if [[ $del_options == "dataset" ]]; then
    datasets=$(h5ls -lr "$file" | awk '/Dataset/ {print $1}' | sed 's/://g')

    selected=$(printf "%s\n" "$datasets" | $fzf --multi --border-label " Select dataset(s) to delete ")
    [[ -z "$selected" ]] && echo "No datasets selected." && exit

    delete_args=""
    while IFS= read -r d; do
        delete_args="$delete_args -d $d"
    done <<< "$selected"

    echo "Deleting: $selected"
    python h5x.py delete "$file" $delete_args
    exit
fi

